#define SCORE_GAP_LEADING (-1)
#define SCORE_GAP_TRAILING (-1)
#define SCORE_GAP_INNER (-2)
#define SCORE_MATCH_CONSECUTIVE 200
#define SCORE_MATCH_SLASH 180
#define SCORE_MATCH_WORD 160
#define SCORE_MATCH_CAPITAL 140
#define SCORE_MATCH_DOT 120
